data_ingestion:
    ext: ".npz"
    csv_col:
        img: "image_id"
        label: "lesion_type"
    path_root: "E:/sphine_xray_npz/vindr-spinexr/1.0.0" #"D:/marchine_learning/Projet/medical_project/AI-Clinical-Imaging-Assistant/data/vindr-spinexr"
    multiclass: false
    paths_img: ["train_images", "test_images"]
    paths_csv: ["annotations/train.csv",  "annotations/test.csv"]
    samples_rate: [0.01, 0.01]
    seed: 50

data_transformation:
    cache_num_workers: 4
    load_image:
        image_size: [128, 128]
        z_score: true
        mean: null
        std: null 
        quantile: [0.01, 0.99]

    cache_rate: [0.01, 0.01]
    flip:
        prob: 0.2
        axis: 1
    contrast:
        prob: 0.2
        gamma: [0.8, 1.2]
    gaussian_noise:
        prob: 0.2
        std: 0.02
    affine:
        prob: 0.2
        rotate: 30
        scale: [0.8, 1.2]
        translate: [-15, 15]
        pad_mode: "border"

loader:
    batch_size: 4
    loader_params:
        num_workers: 4
        pin_memory: true
        prefetch_factor: 4
        persistent_workers: false
        drop_last: true

model_params:
    dropout_rate: [0.1, 0.1]
    in_chans: 1
    feature_head: 128
    model_name: "efficientnet_b0"
    num_classes: 4
    pretrained: true
    uuid_tag: "sssd"

early_stopping:
    patience: 2
    min_delta: 1.0e-7
    monitor: "loss"
    mode: "min"

trainer_config:
    epochs: 2
    accumulation_steps: 2
    lr: 1.0e-4
    max_grad_norm: 1.0
    artifacts_root: "D:/marchine_learning/Projet/medical_project/AI-Clinical-Imaging-Assistant/checkpoint/"
    step_freq_save: 4
    amp: ""
    compile_model: false
    
losses:
    gamma: 0.0
    class_weight: false
    pos_weight: True
    label_smoothing: 0.1
    reduction: "mean"

optimizer:
    name: "AdamW"
    optimizer_params:
        lr: !!float 0.001 
        weight_decay: !!float 1e-2 
        betas: [0.9, 0.99]

scheduler:
    name: "CosineAnnealingLR"   #"CosineAnnealingLR"  CosineAnnealingWarmRestarts
    warmup_epochs: 5
    scheduler_params:
        T_max: 100
        eta_min: !!float 1e-6

wandb_logging:
    project_name: "VinDr_Classification"
    entity: "borel237"
    run_name: "efficientnet_b0"
    sweep_state: false